### ISSUE TITLE
Connection snapping

### ISSUE THREAD

**Issue by i3anaan** [wandernauta/viskell#100]
It might be a pleasant UI upgrade to let the connections snap a bit to anchor points. This should work when dragging, allowing a user to hover a connection over an anchor point, see the results, and then possibly move the connection somewhere else, without having to release it.

**Comment by TheMSB** [comment]
I believe this has been discussed before and personally I do not think snapping is such a good idea, it removes some of of the freedom of the user and assumes you know what they want to do.
