### ISSUE TITLE
ValueBlock multiple types

### ISSUE THREAD

**Issue by TheMSB** [wandernauta/viskell#102]
ValueBlock needs to be able to support multiple types, not just in data model but also UI wise, meaning that it needs a way to change it's type and value.

**Comment by jjkester** [comment]
Changing the value seems like a valid requirement, but I would opt for a fixed type (that can be chosen/specified at creation time).

Maybe we could just have an input field and ask GHCI what the type is?

**Comment by TheMSB** [comment]
My idea was that the contextMenu could toggle an edit state on the value block where you could use a spinner to select the type and a slider for the value.
