### ISSUE TITLE
Context menu polish

### ISSUE THREAD

**Issue by i3anaan** [wandernauta/viskell#107]
Animation needs to be faster / interruptable
New icons
Some user interactivity

**Comment by TheMSB** [comment]
@i3anaan  Can you specify the problems with the animation in detail? I would like to understand the issue before 'fixing' it.

What do you mean by "Some user interactivity"?

**Comment by i3anaan** [comment]
The animation is currently somewhat slow, but more importantly, uninterruptable.
When the animation starts and you try to pan, the pane instantly jumps to a position (The pane pans in such a way that the context menu jumps to your mouse). This is annoying.
On top of that am I getting the feeling that it opens on things it should not open on (anchors), not too sure about that. Might be that it opens to fast sometimes, hard to explain, mostly just feels off.

What I ment with user interactivity is showing that the buttons are buttons, for example by becoming brighter when you hover above them, and possibly also give visual feedback when clicked.

**Comment by TheMSB** [comment]
So I fixed the animation speed, as for your other points:

- Keep in mind we are using a touch interface, there is no hover over state. I have no idea how you would want me to implement an icon light up or something when I 'hover' over the button.

- If we are using touch visual feedback in general for a button seems like a bad idea, when I press something my finger is on top of it, I won't see any of the stuff happen. Most modern 'flat' UI styles do not feature any such thing either.
