### ISSUE TITLE
FunctionBlocks resizing too late

### ISSUE THREAD

**Issue by i3anaan** [wandernauta/viskell#118]
FunctionBlocks are resized too late, to my believe 1 layout pass too late.
I narrowed down the issue to the prefWidthProperty being set correctly, yet the widthProperty not updating until the next pulse.
This causes the FunctionBlocks to spawn with an incorrect width, and also lagging 1 frame behind when for example dragging the knot.

I am out of ideas on how to solve this, widthProperty is supposed to be set by the parent, but the same issue occurs when using a normal Pane instead of the TactilePane as parent.

I have made a stackoverflow question about this:
http://stackoverflow.com/questions/31052912/javafx-widthproperty-not-refreshing

**Comment by TheMSB** [comment]
I've been trying to understand the exact problem but still do not fully grasp it. Could you write down a step by step on how I can observe the behaviour you are speaking about?

**Comment by i3anaan** [comment]
There are several ways of making it noticable:
- Spawn a block and notice that it is way too small.
- Carefully move the knot to the point (frame) where its index changes and the arguments aswell, in most cases the arguments are now larger then the block. (but if you keep moving it resizes sort of correctly again, this one is really precise.
- Connecting blocks, making the arguments change text and thus length
- Everything where the total argument length suddenly changes.

**Comment by TheMSB** [comment]
This has been fixed If I am not mistaken?

**Comment by i3anaan** [comment]
Yes, in UI-2
