### ISSUE TITLE
Add wire splitters and joiners

### ISSUE THREAD

**Issue by comonoidial** [wandernauta/viskell#158]
Constructing and matching on tuples is a very common thing to do, and joining/splitting wires seems a very natural metaphor.
I think we should add a special nameless block for both a splitter and a joiner.
As this is a very basic variation on pattern matching, it might be something for @Flumble to start with.
The main complication is that splitters need multiple outputs.

**Comment by wandernauta** [comment]
As a first step, I think a shortcut to the `(,)` function would work well as a (2-way) joiner.

**Comment by comonoidial** [comment]
Resolved by #360.
