### ISSUE TITLE
Fix UI updating of disconnections and recovery from type errors

### ISSUE THREAD

**Issue by comonoidial** [wandernauta/viskell#183]
Disconnecting a wire does not update all types correctly, especially other arguments of functions blocks.
A connection often stays in error state when you have solved to source of the type error elsewhere.

**Comment by comonoidial** [comment]
I'm surprised that it sometimes works at all, now that have seen Block.cascadeConnectionState and FunctionBlock.invalidateConnectionState.

**Comment by comonoidial** [comment]
@Flumble: do you know of any case where this is still a problem?

**Comment by Flumble** [comment]
After PR #228 a visual update bug still appears when attaching an (partially) inferred type down to an incompatible type. (e.g. feed a list to the _id_ function and then connect the _id_ down to a _not_) The typechecking is performed correctly, but the visual update is done only partially.

A similar partial update is seen when removing the offending connection before its visual state is updated to show the error. Note that this is only a symptom of the above.

**Comment by Flumble** [comment]
Resolved in #236
