### ISSUE TITLE
Displaying types in the UI seems all over the place

### ISSUE THREAD

**Issue by comonoidial** [wandernauta/viskell#188]
See the following two examples, and look at the difference between these.
![wierd_types](https://cloud.githubusercontent.com/assets/14928502/10318679/dfe1e892-6c6a-11e5-8f5c-236ebef15b1d.png)
![weird_types2](https://cloud.githubusercontent.com/assets/14928502/10318684/e611ca2a-6c6a-11e5-9a30-3b241c1d0bb1.png)

**Comment by Flumble** [comment]
Fixed in #217
