### ISSUE TITLE
Function application deserves it own kind of block

### ISSUE THREAD

**Issue by comonoidial** [wandernauta/viskell#194]
Currently it is easy to create blocks that have a function as an output, by currying or definition blocks.
But when an input is a function using it is inconvenient and one has to use combinators like ($).
For example see what is needed now to implement something alike to the standard library function:
on :: (b -> b -> c) -> (a -> b) -> (a -> a -> c)

Using functions is as important as creating them, so a special function block would be nice to have.
It could be like a function block that takes a function wire instead of a name, or maybe someone has a better idea.

**Comment by wandernauta** [comment]
Agreed - it could even be something as simple as this:

![mockup](https://cloud.githubusercontent.com/assets/126832/10455026/02f0e5f6-71b9-11e5-9096-f056a696cbda.png)

That would compile to either a use of `($)` or just an application, I'm not sure if there's any difference.

**Comment by comonoidial** [comment]
I would prefer something more specialized.
Having the function type as first element is superfluous information.
Also the bowtie thing makes no sense for single argument functions, and currently behaves oddly on ($) with multi-argument functions.

**Comment by comonoidial** [comment]
Resolved in #374 plus #384.
