### ISSUE TITLE
Types of value and slider blocks are wrong

### ISSUE THREAD

**Issue by comonoidial** [wandernauta/viskell#215]
Value blocks seem to remember their old type even after a full disconnect, which makes them not reusable and causing unnecessary type errors.
Slider block now always have the type Float as output, this is a poor default and too restrictive.

**Comment by wandernauta** [comment]
Maybe the slider block could be turned into a block with two inputs (min, max) and one output, then base the output type on the input type.

**Comment by comonoidial** [comment]
While generalizing slider blocks is a good idea, it is not how the typing problem should be solved.
Also by requiring extra inputs the slider block will be less convenient to use, because where do these inputs come from? (another slider block, oops...)

**Comment by wandernauta** [comment]
The inputs wouldn't need to be required - they could default to 0.0 and 1.0 respectively.

**Comment by comonoidial** [comment]
Fixed in #218.
