### ISSUE TITLE
Lambda result/argument types (x_0) do not get turned into real types

### ISSUE THREAD

**Issue by wandernauta** [wandernauta/viskell#219]
I'd expect every type outside the lambda block to just be `Float`.

![Screenshot](https://cloud.githubusercontent.com/assets/126832/10848734/9cd37ca8-7f1d-11e5-92d7-ffbded9da0b0.png)

**Comment by comonoidial** [comment]
Solved by #221, but in the long term it might be better to have both an external and internal block(s) for each lambda and case like construct.
