### ISSUE TITLE
Typechecker bug for type class constraints on higher-order types

### ISSUE THREAD

**Issue by Flumble** [wandernauta/viskell#220]
For example, feeding the result of _fmap_ (further type constraints don't matter) to _(<)_ (anything with a type constraint) results in an error, whereas it should add type constraints to the functor in _fmap_.

This may be related to #207

**Comment by comonoidial** [comment]
This is a known limitation of the current simplified implementation of typeclasses, where constraints can only exists on type variables and not type applications.
I do intend to improve this sometime, but as it is a bigger change I will treat it as lower priority request unless this is triggered more often.

**Comment by comonoidial** [comment]
This make whether typechecking succeeds depending on the order of connections that are unified for types, and that is bad.

**Comment by Flumble** [comment]
Fixed in #309
