### ISSUE TITLE
Dealing with scope restrictions on connections

### ISSUE THREAD

**Issue by comonoidial** [wandernauta/viskell#222]
Currently drawing of connections is unrestricted, even if it is impossible from scoping point of view.
For example you can connect the internal top anchor of a lambda to anything which can lead to generation of bad code where the binder escapes the lambda.
The question is how to best prevent this.
One option is to treat scope errors as a variation on type errors, or maybe even block connection lines from escaping a lambda block.
Similar issues will arise with the eventual case constructs.

**Comment by wandernauta** [comment]
Blocking connection lines from leaving a lambda block will break reusing constant subexpressions:

![Screenshot](https://cloud.githubusercontent.com/assets/126832/10869260/c73b0276-80a9-11e5-9118-26732164ca1a.png)

This could either be an upside or a downside depending on your point of view.

**Comment by comonoidial** [comment]
In my opinion only the (,) block is truly part of the lambda as it depends on the binder.
So in this case the connection line to the display should not be blocked.

**Comment by wandernauta** [comment]
I agree. However, it could turn out to be nontrivial to make and explain these decisions.

**Comment by Flumble** [comment]
This is kind of solved in #298 and #300 by allowing a display block inside a container and not parsing connections that come from an inner container. If we consider this a solution, it only needs visual feedback when the destination of a connection is outside of the source's container.

**Comment by comonoidial** [comment]
@wandernauta do you consider this issue solved with #319, or is there more to be done here?
