### ISSUE TITLE
Support functionless function blocks

### ISSUE THREAD

**Issue by comonoidial** [wandernauta/viskell#229]
At the moment you have first select an exact function from the less practical function menu, and then connect it to where you want to use it, but often you would like to do that in other way around.
So starting with an functionless block with a certain number of arguments to connect, and then after connecting the inputs, use the avaible types to select a fitting function for this block (filtered to a convenient small set based on types).

**Comment by wandernauta** [comment]
This could be the apply-anything block I drew in #194. You'd attach your arguments, then maybe touch the spot where the function name is supposed to go to get a list of matching functions, as in #223. Picking a function would turn the block into a regular function block.

**Comment by comonoidial** [comment]
Having thought about this more, this is indeed as #194 with a little extra user interface.
