### ISSUE TITLE
Make the function menu less annoying to use

### ISSUE THREAD

**Issue by comonoidial** [wandernauta/viskell#230]
This needs no further comments, just trying to use it will show multiple shortcomings.

**Comment by wandernauta** [comment]
Neverless, specifying the shortcomings could make for a clearer issue report, as it's a bit vague as is.

**Comment by comonoidial** [comment]
Let's try to make a start:
* it wastes too much space
* function categories should not expand down in an already vertical menu
* the menu should not appear partially offscreen
* also should not expand into offscreen
* please no scrollbars
* expanded categories should not have empty lines
* it is visually inconsistent
* the current grouping in categories itself is of little use, unless you know what to find where
* alphabetic ordering is not good with many rarely used items and lots of operators
* uncommon blocks should not be on the first row

**Comment by wandernauta** [comment]
A way to deal with much of the positioning and layout stuff could be to use a regular JavaFX ContextMenu, at least on non-touch devices, as it automatically positions itself in a sensible way so that it doesn't move offscreen. Another advantage is that it has a consistent size that doesn't depend on the zoom level, and that people are used to the way it works.

The grouping and ordering things could perhaps be approached, again at least on non-touch devices, by adding (prefix-, type- or fuzzy) keyboard-based search.

**Comment by comonoidial** [comment]
And I forgot one important thing, that is being able to drag new block from the function menu to the location you want them. Having a click menu stack them all in one spot is very inconvenient.

**Comment by comonoidial** [comment]
Oops did overlook #164, let's continue here.

**Comment by Flumble** [comment]
From https://github.com/wandernauta/viskell/pull/304#issuecomment-163381402

  * The margins around the buttons could perhaps use some fiddling around with to make them look neater
  * I get the extra Close button from a balance standpoint, but I don't think it's good UX - if people see a close button at that position, they will get used to it being there. 'Suddenly' hiding it when the user switches backend would then not be ideal. I'd prefer to just leave the space blank (or purple).
  * ...aaand when you're playing around with the FunctionMenu css anyway - maybe the Close button could use a splash of color to help distinguish it from the others?

**Comment by comonoidial** [comment]
I think basicly all that can be improved with this style of function menu has been done.
Further non trivial improvement will require a complete redesign.
