### ISSUE TITLE
Add data constructor/deconstructor blocks

### ISSUE THREAD

**Issue by comonoidial** [wandernauta/viskell#233]
Data constuctors are not quite functions, and easy recognizable in Haskell as they start by a capital letter.
They deserve a specially shaped variant of a function block.
And for use in pattern match/case expression the same sort of block could be used but then upside down.
Also data constructors seem to be missing in the catalog.
Related issue is #158 and #154.

**Comment by wandernauta** [comment]
If I understand it correctly, that means you'd have `Just 10` as a data constructor block of `Just` and a value block of `10`, instead of as a single value block?

**Comment by comonoidial** [comment]
Yes, but using a single value block for them would still be possible.
Now value blocks are a bit abused for everything that is not supported or inconvenient

**Comment by Flumble** [comment]
Deconstructor blocks in general should wait until there is a case block, since you can't just deconstruct a sum type.
A deconstructor block for the (n-)tuple would be nice for now, although this should probably be a special shape on its own, together with the (n-)tuple constructor.

**Comment by comonoidial** [comment]
Not all constructors are sumtypes, and then you have the special case of constructors that are newtypes.

**Comment by comonoidial** [comment]
Deconstructors seems to be finished by #414.
