### ISSUE TITLE
Add boolean constructors to catalog 

### ISSUE THREAD

**Issue by wandernauta** [wandernauta/viskell#237]
The `True` and `False` data constructors would be useful to have in the catalog.

**Comment by comonoidial** [comment]
What about all the other basic (only a few) data constructors from the Prelude?

**Comment by wandernauta** [comment]
`Maybe a` and `Either a b`, you mean?

**Comment by comonoidial** [comment]
Yes, and [] and Ordering.

**Comment by wandernauta** [comment]
Okay, will do.
