### ISSUE TITLE
Remove useless GHCi setup/teardown in Main

### ISSUE THREAD

**Issue by wandernauta** [wandernauta/viskell#256]
GHCi can take some time to boot up (on the order of a few seconds on older hardware), which makes this bit in Main a bit wasteful:

        // Check if GHCI is available
        try {
            GhciEvaluator testGhci = new GhciEvaluator(); 
            testGhci.eval("");
            testGhci.close();
        } catch (HaskellException e) {
            // ...
        }

It would make more sense to either reuse `testGhci` or rethink the error case entirely.

**Comment by comonoidial** [comment]
Reusing testGhci and let it start up happen in a seperate thread makes sense.

**Comment by comonoidial** [comment]
Resolved in #370.
