### ISSUE TITLE
Add datatypes and their constructors as specialized information to the catalog

### ISSUE THREAD

**Issue by comonoidial** [wandernauta/viskell#257]
Now data constructors are treated just as functions, this sort of works but we need more information on datatypes than just the type of the constructors.

**Comment by wandernauta** [comment]
GHCi seems to treat datatype constructors as functions as well, at least in some cases:

    Prelude> :t Just
    Just :: a -> Maybe a
    Prelude> map Just [1,2,3,4]
    [Just 1,Just 2,Just 3,Just 4]

What additional information were you thinking about?

**Comment by comonoidial** [comment]
That for example that the type Maybe consist of constructor Nothing and Just.
And know which catalog entries are constructors that can be pattern matched on.

**Comment by comonoidial** [comment]
Resolved in PR #295
