### ISSUE TITLE
Figure out bad event handling on the large touchscreen

### ISSUE THREAD

**Issue by comonoidial** [wandernauta/viskell#267]
On the large touchscreen some touch events don't seem to register properly.
Also dragging blocks is more like stuttering that covers half the distance.
Other applications don't behave this bad with touch, something is wrong with the current implementation.

**Comment by comonoidial** [comment]
And also the debug mode of the tactile pane should be reenabled (by a menu option?).

**Comment by Flumble** [comment]
"Fixed" in #274
