### ISSUE TITLE
Split graphics into multiple layers

### ISSUE THREAD

**Issue by comonoidial** [wandernauta/viskell#269]
Currently all graphical elements are one big list of things, keeping the stacking order look good and usable becomes increasingly hard.
A solution is to divide graphical elements over a few layers:
The bottom layer will be block 'containers' such as lambdas, cases and current toplevel.
Next layer are the normal blocks as functions, values and displays.
Then a layer with all the wires connecting things without being accidently obscured.
And the top layer will be menu like things and blocks be dragged around.
One complication is that currently tactilefx doesn't deal well with hierachy.

**Comment by wandernauta** [comment]
There doesn't really have to be a hierarchy - as long as we can keep the CustomUIPane's children sorted by 'layer' we should be all right.

**Comment by comonoidial** [comment]
That is not so easy because of Node.toFront() being called in various places.
