### ISSUE TITLE
Invalidate type restriction in definition blocks w.r.t their signature

### ISSUE THREAD

**Issue by Flumble** [wandernauta/viskell#301]
Currently when defining a definition block with a type variable, the result type can be restricted to a concrete type (or have additional type classes).
However, a result type should be *at least as generic* as the definition's signature.

A possible fix would be to check if the type feeding into the result anchor does not add restrictions to the signature's result type when unified.

Example of an offending type restriction:
![shot_1226](https://cloud.githubusercontent.com/assets/904938/11686315/1245d7c0-9e80-11e5-9192-1651a8a41a2f.png)

**Comment by comonoidial** [comment]
Solved by #305.
