### ISSUE TITLE
Flickering when currying horizontally-curried applications

### ISSUE THREAD

**Issue by wandernauta** [wandernauta/viskell#390]
When currying functions with the 'Vertical curry' preference turned off, the width of the FunctionBlock varies ('flickers') whenever the mouse is moved.

This seems to be introduced by 98a30f80565fa15486511e69a01392728fb35ebf.

**Comment by comonoidial** [comment]
I only notice flickering when moving the knot, do you mean it is happening with mouse moves anywhere?
The implementation of knot moving is a bit of hack, that last bind may be one to many.
I'm fine with removing that centering bind for the FunctionBlock specifically.

**Comment by wandernauta** [comment]
No, the flickering only occurs when moving the knot. Moving the entire block seems to work fine.
