### ISSUE TITLE
Types not propagated upwards

### ISSUE THREAD

**Issue by wandernauta** [wandernauta/viskell#85]
It seems type information is not propagated upwards, as it should:

![bug2](https://cloud.githubusercontent.com/assets/126832/7555645/45e69a4a-f752-11e4-9ab8-98762680009d.png)

a, 35 and 38 can all only be Float.

((+) has been modified to `Float -> Float -> Float` for this example to avoid the issue from #83.)

**Comment by i3anaan** [comment]
Wat ik van JJ heb begrepen was dit niet iets wat makkelijk te implementeren was.

**Comment by wandernauta** [comment]
We implementeren wel meer dingen die niet makkelijk zijn toch? :)

**Comment by i3anaan** [comment]
Klopt, wat ik misschien meer bedoelde was dat ik dit eerder al min of meer gevraagd had, en JJ mij de indruk gaf dit niet te verwachten.

**Comment by i3anaan** [comment]
Dit levert problemen op als er een block met type a naar 2 blocken gaat met verschillende types b en c, dan zou a zowel b als c worden volgens omhoog propagatie, waarbij b en c niet hoeven te unificeren.

Dit zou dus ook niet heel veel meer dan een visueel foefje zijn die alleen werkt als er maar 1 type omhoog gepropageerd wordt.

**Comment by wandernauta** [comment]
Hmm. Het is denk ik wel meer dan een visueel foefje: het geeft aan wat je op een inputanchor kunt aansluiten, wat wel vrij belangrijke informatie is, lijkt me.

**Comment by i3anaan** [comment]
Het is niet echt belangrijke informatie, het voegt geen nieuwe informatie toe. Het kan wel handige / makkelijke informatie zijn.
