### ISSUE TITLE
Hindley Milner log spam

### ISSUE THREAD

**Issue by i3anaan** [wandernauta/viskell#88]
Ik wordt eerlijk gezegd vrij moe van de rode spam van hindley milner die ik toch niet snap, zou hier een  toggle of iets voor kunnen komen?

**Comment by wandernauta** [comment]
Ik denk eigenlijk dat het wel nuttig is om te kunnen lezen wat er met wat geunified wordt. Dat je niet snapt wat er staat kunnen wij verder niet zo veel aan doen - als je betere log messages weet mag je een PR inschieten.

**Comment by i3anaan** [comment]
Ik heb er wat moeite mee dat dit wel toegelaten wordt, maar mijn melding dat invalidation inefficiënt gebeurt niet.

**Comment by wandernauta** [comment]
Als je er echt last van hebt kun je de HindleyMilner-klasse aanpassen: die gebruikt een standaard Java [`Logger`](https://docs.oracle.com/javase/7/docs/api/java/util/logging/Logger.html). Op die logger zou je bijvoorbeeld `setLevel` kunnen aanroepen als je geen interesse hebt in info-level berichten.

Als je dat wilt zou je zelfs de hele Java logging-architectuur naar binnen kunnen trekken en logging kunnen configureren op basis van een `properties`-file, of iets als [slf4j](http://www.slf4j.org/) of [log4j](https://logging.apache.org/log4j/2.x/) kunnen gebruiken. 't is alleen dat tot nu toe niemand daar de tijd voor heeft genomen omdat er nog maar één onderdeel is dat daadwerkelijk logt.
